# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.134.1/containers/javascript-node/.devcontainer/base.Dockerfile
ARG VARIANT="14"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

RUN cd / \
    && RUN npm install -g http-server \
    && git clone --branch master https://github.com/audstanley/web-frontend-hw \
    && mv web-frontend-hw code \
    && cd code \
    && chmod +x entrypoint.sh;